import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Badge } from '../../components/Badge';
import { Button } from '../../components/Button';
import { Card } from '../../components/Card';
import { ConfirmDialog } from '../../components/ConfirmDialog';
import { Container } from '../../components/Container';
import { EditMemoryModal } from '../../components/EditMemoryModal';
import { EmptyState } from '../../components/EmptyState';
import { Header } from '../../components/Header';
import { KebabMenu } from '../../components/KebabMenu';
import { ShareMenu } from '../../components/ShareMenu';
import { LoadingState } from '../../components/LoadingState';
import { TextArea } from '../../components/TextArea';
import { formatMemoryDate } from '../../lib/date/formatMemoryDate';
import { sortMemories } from '../../lib/date/sortMemories';
import { deriveTitle } from '../../lib/text/deriveTitle';
import { track } from '../../lib/track/track';
import { useToast } from '../../lib/toast/useToast';
import { useCreateMemory } from '../../hooks/useCreateMemory';
import { useDeleteMemory } from '../../hooks/useDeleteMemory';
import { useMemoriesTimeline } from '../../hooks/useMemoriesTimeline';
import { useMyStory } from '../../hooks/useMyStory';
import { useUpdateMemory } from '../../hooks/useUpdateMemory';
import { useGenerateStory } from '../../hooks/useGenerateStory';
import { useAuth } from '../auth/AuthProvider';
import type { DateType, MemoryUI } from '../../types/memory';

declare global {
  interface WindowEventMap {
    beforeinstallprompt: BeforeInstallPromptEvent;
  }
}

type BeforeInstallPromptEvent = Event & {
  prompt: () => Promise<void>;
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }>;
};

const INITIAL_VISIBLE_MEMORIES = 10;
const INCREMENT_MEMORIES = 10;
const MAX_TITLE_LENGTH = 120;
const MIN_MEMORIES_FOR_STORY = 3;

function getFirstStorySeen(): boolean {
  try {
    return localStorage.getItem('firstStoryGenerated') === 'true';
  } catch {
    return false;
  }
}

function markFirstStorySeen() {
  try {
    localStorage.setItem('firstStoryGenerated', 'true');
  } catch {}
}

function getDisplayTitle(memory: MemoryUI): string {
  if (memory.title && memory.title.trim() && memory.title !== 'Sem título') {
    return memory.title;
  }
  return deriveTitle(memory.content);
}

export function HomePage() {
  const { showToast } = useToast();
  const { userId, isReady } = useAuth();
  const createMemoryMutation = useCreateMemory();
  const memoriesQuery = useMemoriesTimeline(userId);
  const storyQuery = useMyStory(userId);
  const generateStoryMutation = useGenerateStory();
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [dateType, setDateType] = useState<DateType | null>(null);
  const [customDate, setCustomDate] = useState('');
  const [customYear, setCustomYear] = useState('');
  const [customAge, setCustomAge] = useState('');
  const [installPromptEvent, setInstallPromptEvent] = useState<BeforeInstallPromptEvent | null>(null);
  const hasTrackedAppOpen = useRef(false);
  const hasAutoGenerated = useRef(false);
  const [firstStorySeen, setFirstStorySeen] = useState(getFirstStorySeen);

  const [visibleCount, setVisibleCount] = useState(INITIAL_VISIBLE_MEMORIES);

  const handleShowMore = useCallback(() => {
    setVisibleCount((prev) => prev + INCREMENT_MEMORIES);
  }, []);

  const currentYear = new Date().getFullYear();

  function getFullDateError(): string | null {
    if (!customDate || dateType !== 'FullDate') return null;
    const parts = customDate.split('/');
    if (parts.length !== 3 || parts.some((p) => p.length === 0)) return 'Use o formato dd/mm/aaaa.';
    const year = parseInt(parts[2], 10);
    if (year < 1900 || year > currentYear) return `O ano deve estar entre 1900 e ${currentYear}.`;
    const date = new Date(`${parts[2]}-${parts[1]}-${parts[0]}`);
    if (date > new Date()) return 'A data informada Ã© futura.';
    return null;
  }

  function getYearError(): string | null {
    if (!customYear) return null;
    if (!/^\d+$/.test(customYear)) return 'Use apenas nÃºmeros.';
    const y = Number(customYear);
    if (y < 1900 || y > currentYear) return `O ano deve estar entre 1900 e ${currentYear}.`;
    if (y > currentYear) return 'O ano informado Ã© futuro.';
    return null;
  }

  function getAgeError(): string | null {
    if (!customAge) return null;
    if (!/^\d+$/.test(customAge)) return 'Use apenas nÃºmeros.';
    const a = Number(customAge);
    if (a < 0 || a > 120) return 'A idade deve ser entre 0 e 120.';
    return null;
  }

  useEffect(() => {
    if (hasTrackedAppOpen.current) return;
    track('app_opened');
    hasTrackedAppOpen.current = true;
  }, []);

  useEffect(() => {
    const handleBeforeInstallPrompt = (event: BeforeInstallPromptEvent) => {
      event.preventDefault();
      setInstallPromptEvent(event);
    };
    window.addEventListener('beforeinstallprompt', handleBeforeInstallPrompt);
    return () => window.removeEventListener('beforeinstallprompt', handleBeforeInstallPrompt);
  }, []);

  const allMemories = useMemo(() => {
    return sortMemories(memoriesQuery.data?.memories ?? []);
  }, [memoriesQuery.data?.memories]);

  const memories = useMemo(() => {
    return allMemories.slice(0, visibleCount);
  }, [allMemories, visibleCount]);

  const hasMoreMemories = allMemories.length > memories.length;

  const memoriesData = memoriesQuery.data?.memories;
  const hasMemoriesData = Array.isArray(memoriesData);
  const successMemories = useMemo(() => allMemories.filter((m) => m.status === 'success'), [allMemories]);

  useEffect(() => {
    if (storyQuery.data?.story && !firstStorySeen) {
      setFirstStorySeen(true);
      markFirstStorySeen();
    }
  }, [storyQuery.data?.story, firstStorySeen]);

  const isFirstStoryNotGenerated = !storyQuery.data?.story && !storyQuery.isLoading && !storyQuery.isError;
  useEffect(() => {
    if (
      successMemories.length >= MIN_MEMORIES_FOR_STORY &&
      isFirstStoryNotGenerated &&
      !hasAutoGenerated.current &&
      !generateStoryMutation.isPending
    ) {
      hasAutoGenerated.current = true;
      showToast({
        message: 'Sua primeira história está sendo gerada...',
        variant: 'info',
      });
      generateStoryMutation.mutate(
        { userId },
        {
          onSuccess: () => {
            showToast({
              message: 'Sua primeira história está pronta!',
              variant: 'success',
            });
            void storyQuery.refetch();
          },
          onError: () => {
            hasAutoGenerated.current = false;
            showToast({
              message: 'Não foi possível gerar sua história agora. Tente novamente mais tarde.',
              variant: 'error',
            });
          },
        },
      );
    }
  }, [successMemories.length, isFirstStoryNotGenerated, userId, generateStoryMutation, showToast, storyQuery]);

  const handleCopyStory = useCallback(() => {
    const story = storyQuery.data?.story;
    if (!story) return;
    const text = story.title ? `${story.title}\n\n${story.content}` : story.content;
    navigator.clipboard.writeText(text).then(() => {
      showToast({ message: 'História copiada com sucesso.', variant: 'success' });
    }).catch(() => {
      showToast({ message: 'Não foi possível copiar a história.', variant: 'error' });
    });
  }, [storyQuery.data?.story, showToast]);

  const [isShareMenuOpen, setIsShareMenuOpen] = useState(false);

  const handleGenerateStory = useCallback(() => {
    track('story_generate_clicked');
    generateStoryMutation.mutate(
      { userId },
      {
        onSuccess: () => {
          showToast({
            message: 'História atualizada com sucesso.',
            variant: 'success',
          });
          void storyQuery.refetch();
        },
        onError: (error: unknown) => {
          const msg =
            error && typeof error === 'object' && 'message' in error
              ? (error as { message: string }).message
              : 'Não foi possível gerar sua história.';
          showToast({ message: msg, variant: 'error' });
        },
      },
    );
  }, [userId, generateStoryMutation, showToast, storyQuery]);

  const handleInstallApp = async () => {
    if (!installPromptEvent) {
      showToast({
        message: 'A instalação ainda não está disponível neste navegador.',
        variant: 'info',
      });
      return;
    }
    await installPromptEvent.prompt();
    const choice = await installPromptEvent.userChoice;
    if (choice.outcome === 'accepted') {
      showToast({ message: 'App instalado com sucesso.', variant: 'success' });
    }
    setInstallPromptEvent(null);
  };

  const [editingMemory, setEditingMemory] = useState<MemoryUI | null>(null);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [deletingMemory, setDeletingMemory] = useState<MemoryUI | null>(null);
  const [isDeleteConfirmOpen, setIsDeleteConfirmOpen] = useState(false);

  const updateMemoryMutation = useUpdateMemory();
  const deleteMemoryMutation = useDeleteMemory();

  const handleOpenEdit = useCallback((memory: MemoryUI) => {
    if (memory.status === 'pending') return;
    setEditingMemory(memory);
    setIsEditModalOpen(true);
  }, []);

  const handleCloseEdit = useCallback(() => {
    setIsEditModalOpen(false);
    setEditingMemory(null);
  }, []);

  const handleSaveEdit = useCallback(
    (payload: { title?: string; content: string; isImportant: boolean; dateType?: DateType; eventDate?: string; eventYear?: number; age?: number }) => {
      if (!editingMemory) return;
      updateMemoryMutation.mutate(
        { memoryId: editingMemory.id.startsWith('temp-') ? '' : editingMemory.id, userId, payload },
        {
          onSuccess: () => {
            showToast({ message: 'Memória atualizada.', variant: 'success' });
            handleCloseEdit();
          },
          onError: (error) => {
            const msg = error && typeof error === 'object' && 'message' in error
              ? (error as { message: string }).message
              : 'Não foi possível atualizar a memória.';
            showToast({ message: msg, variant: 'error' });
          },
        },
      );
    },
    [editingMemory, userId, updateMemoryMutation, showToast, handleCloseEdit],
  );

  const handleOpenDelete = useCallback((memory: MemoryUI) => {
    if (memory.status === 'pending') return;
    setDeletingMemory(memory);
    setIsDeleteConfirmOpen(true);
  }, []);

  const handleCloseDelete = useCallback(() => {
    setIsDeleteConfirmOpen(false);
    setDeletingMemory(null);
  }, []);

  const handleConfirmDelete = useCallback(() => {
    if (!deletingMemory) return;
    deleteMemoryMutation.mutate(
      { memoryId: deletingMemory.id.startsWith('temp-') ? '' : deletingMemory.id, userId },
      {
        onSuccess: () => {
          showToast({ message: 'Memória excluída.', variant: 'success' });
          handleCloseDelete();
        },
        onError: (error) => {
          const msg = error && typeof error === 'object' && 'message' in error
            ? (error as { message: string }).message
            : 'Não foi possível excluir a memória.';
          showToast({ message: msg, variant: 'error' });
        },
      },
    );
  }, [deletingMemory, userId, deleteMemoryMutation, showToast, handleCloseDelete]);

  const canSubmit = Boolean(content.trim()) && !createMemoryMutation.isPending;

  if (!isReady) {
    return (
      <main className="page-shell">
        <Container>
          <Card className="hero-card">
            <LoadingState label="Preparando sua história..." />
          </Card>
        </Container>
      </main>
    );
  }

  return (
    <main className="page-shell">
      <Container>
        <Card className="hero-card">
          <Header
            title="Bem-vindo ao MakeMyHistory"
            subtitle="Registre memórias, acompanhe sua timeline e acompanhe sua história pessoal."
            action={
              <div className="section-actions">
                <Badge variant="default">MVP</Badge>
                <Button
                  type="button"
                  variant="secondary"
                  disabled={!installPromptEvent}
                  onClick={handleInstallApp}
                >
                  {installPromptEvent ? 'Instalar app' : 'Instalação indisponível'}
                </Button>
              </div>
            }
          />

          <div className="home-layout">
            <div className="home-layout__row home-layout__row--top">
              <section className="panel-card">
                <Header title="Nova memória" subtitle="Fluxo principal" />
                <div className="memory-form">
                  <label className="input-field" htmlFor="memory-title">
                    <span className="input-field__label">Título opcional</span>
                    <input
                      id="memory-title"
                      className="input"
                      type="text"
                      value={title}
                      placeholder="Ex.: Viagem para o litoral"
                      maxLength={MAX_TITLE_LENGTH}
                      onChange={(event) => setTitle(event.target.value)}
                    />
                  </label>
                  <div className="input-footer">
                    <span className="timeline-count">{title.length} / {MAX_TITLE_LENGTH}</span>
                  </div>
                  <TextArea
                    id="memory-content"
                    label="Conteúdo"
                    placeholder="Escreva um momento importante..."
                    value={content}
                    autoFocus
                    onChange={(event) => setContent(event.target.value)}
                    rows={4}
                    maxLength={500}
                  />
                  <div className="input-footer">
                    <span className="timeline-count">{content.length} / 500</span>
                  </div>

                  <div className="date-type-selector">
                    <span className="date-type-selector__label">+ Quando isso aconteceu?</span>
                    <div className="date-type-options">
                      {(['FullDate', 'YearOnly', 'Age'] as DateType[]).map((type) => (
                        <label
                          key={type}
                          className={`date-type-option${dateType === type ? ' date-type-option--selected' : ''}`}
                        >
                          <input
                            type="radio"
                            name="dateType"
                            value={type}
                            checked={dateType === type}
                            onChange={() => setDateType(type)}
                          />
                          {type === 'FullDate' ? 'Data completa' : type === 'YearOnly' ? 'Apenas ano' : 'Idade na época'}
                        </label>
                      ))}
                    </div>

                    {dateType === 'FullDate' && (
                      <div className="date-value-input">
                        <input
                          className={['input', getFullDateError() ? 'input--invalid' : ''].filter(Boolean).join(' ')}
                          type="text"
                          value={customDate}
                          onChange={(e) => {
                            const raw = e.target.value.replace(/[^\d/]/g, '');
                            let formatted = raw;
                            if (raw.length === 2 && !raw.includes('/') && customDate.length < 2) formatted = raw + '/';
                            else if (raw.length === 5 && raw[2] === '/' && !raw.slice(3).includes('/') && customDate.length < 5) formatted = raw + '/';
                            setCustomDate(formatted);
                          }}
                          placeholder="dd/mm/aaaa"
                          maxLength={10}
                        />
                        {getFullDateError() ? <span className="date-value-error">{getFullDateError()}</span> : null}
                      </div>
                    )}
                    {dateType === 'YearOnly' && (
                      <div className="date-value-input">
                        <input
                          className={['input', getYearError() ? 'input--invalid' : ''].filter(Boolean).join(' ')}
                          type="text" inputMode="numeric"
                          value={customYear}
                          onChange={(e) => setCustomYear(e.target.value.replace(/[^\d]/g, ''))}
                          placeholder="Ex: 2018" maxLength={4}
                        />
                        {getYearError() ? <span className="date-value-error">{getYearError()}</span> : null}
                      </div>
                    )}
                    {dateType === 'Age' && (
                      <div className="date-value-input">
                        <input
                          className={['input', getAgeError() ? 'input--invalid' : ''].filter(Boolean).join(' ')}
                          type="text" inputMode="numeric"
                          value={customAge}
                          onChange={(e) => setCustomAge(e.target.value.replace(/[^\d]/g, ''))}
                          placeholder="Ex: 25" maxLength={3}
                        />
                        {getAgeError() ? <span className="date-value-error">{getAgeError()}</span> : null}
                      </div>
                    )}
                  </div>

                  <div className="hero-actions">
                    <Button
                      type="button"
                      disabled={!canSubmit}
                      onClick={() => {
                        if (!canSubmit) return;
                        if (navigator.onLine === false) {
                          showToast({ message: 'Sem conexão. Tente novamente quando estiver online.', variant: 'error' });
                          return;
                        }
                        const payload: {
                          userId: string; title?: string; content: string; isImportant: boolean;
                          dateType?: DateType; eventDate?: string; eventYear?: number; age?: number; clientRequestId: string;
                        } = {
                          userId, title: title.trim() || deriveTitle(content.trim()) || undefined, content: content.trim(),
                          isImportant: false, clientRequestId: crypto.randomUUID(),
                        };
                        if (dateType && dateType === 'FullDate' && customDate) {
                          const parts = customDate.split('/');
                          if (parts.length === 3) {
                            const [day, month, yearStr] = parts;
                            const year = parseInt(yearStr, 10);
                            payload.dateType = 'FullDate';
                            payload.eventDate = `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}`;
                            payload.eventYear = year;
                          } else {
                            payload.dateType = 'FullDate';
                            payload.eventDate = customDate;
                          }
                        } else if (dateType === 'YearOnly' && customYear) {
                          payload.dateType = 'YearOnly';
                          payload.eventYear = parseInt(customYear, 10);
                        } else if (dateType === 'Age' && customAge) {
                          const age = parseInt(customAge, 10);
                          payload.dateType = 'Age';
                          payload.age = age;
                          payload.eventYear = new Date().getFullYear() - age;
                        }
                        createMemoryMutation.mutate(payload, {
                          onSuccess: () => {
                            track('memory_created');
                            showToast({ message: `Memória guardada em ${formatMemoryDate(new Date())}.`, variant: 'success' });
                            setTitle(''); setContent(''); setDateType(null); setCustomDate(''); setCustomYear(''); setCustomAge('');
                          },
                          onError: (error) => {
                            const msg = error && typeof error === 'object' && 'message' in error
                              ? (error as { message: string }).message
                              : 'Não foi possível guardar sua memória.';
                            showToast({ message: msg, variant: 'error' });
                          },
                        });
                      }}
                    >
                      {createMemoryMutation.isPending ? 'Guardando...' : 'Salvar memória'}
                    </Button>
                  </div>
                </div>
              </section>

              <section className="panel-card">
                <Header title="Sua História" subtitle="" />

                <div className="story-two-cards">
                  {!storyQuery.data?.story && successMemories.length >= MIN_MEMORIES_FOR_STORY ? (
                    <div className="story-status-card">
                      <div className="story-status-card__title">Sua primeira história está sendo gerada...</div>
                      <p className="story-status-card__counter">Baseada em {successMemories.length} memórias</p>
                    </div>
                  ) : !storyQuery.data?.story && successMemories.length === 0 ? (
                    <div className="story-status-card">
                      <div className="story-status-card__title">Sua história está começando.</div>
                      <p className="story-status-card__desc">Registre memórias para criarmos sua primeira história.</p>
                      <p className="story-status-card__counter"><strong>0</strong> de <strong>{MIN_MEMORIES_FOR_STORY}</strong> memórias para gerar sua primeira história</p>
                    </div>
                  ) : !storyQuery.data?.story && successMemories.length === 1 ? (
                    <div className="story-status-card">
                      <div className="story-status-card__title">Sua história está começando.</div>
                      <p className="story-status-card__desc">Registre mais memórias para criarmos sua primeira história.</p>
                      <p className="story-status-card__counter"><strong>1</strong> de <strong>{MIN_MEMORIES_FOR_STORY}</strong> memórias para gerar sua primeira história</p>
                    </div>
                  ) : !storyQuery.data?.story && successMemories.length === 2 ? (
                    <div className="story-status-card">
                      <div className="story-status-card__title">Sua história está ganhando forma.</div>
                      <p className="story-status-card__desc">Falta apenas mais uma memória para gerar sua primeira história.</p>
                      <p className="story-status-card__counter"><strong>2</strong> de <strong>{MIN_MEMORIES_FOR_STORY}</strong> memórias para gerar sua primeira história</p>
                    </div>
                  ) : storyQuery.data?.story && successMemories.length < MIN_MEMORIES_FOR_STORY ? (
                    <div className="story-status-card story-status-card--done">
                      <div className="story-status-card__title">Sua história foi gerada anteriormente</div>
                      <p className="story-status-card__counter">
                        Atualmente você possui <strong>{successMemories.length}</strong> de <strong>{MIN_MEMORIES_FOR_STORY}</strong> memórias necessárias para gerar uma nova versão.
                      </p>
                      <p className="story-status-card__desc">Adicione mais memórias para atualizar sua história.</p>
                    </div>
                  ) : storyQuery.data?.story && !firstStorySeen ? (
                    <div className="story-status-card story-status-card--done">
                      <div className="story-status-card__title">Sua primeira história está pronta!</div>
                      <div className="story-meta">
                        <span className="story-meta__item">Baseada em {storyQuery.data.story.memoryCount ?? successMemories.length} memórias</span>
                        {storyQuery.data.story.updatedAt ? (
                          <span className="story-meta__item">Atualizada {formatRelativeTime(storyQuery.data.story.updatedAt)}</span>
                        ) : null}
                      </div>
                      {storyQuery.data.isOutOfSync ? (
                        <p className="story-out-of-sync-message">Sua história não inclui as alterações mais recentes.</p>
                      ) : null}
                    </div>
                  ) : storyQuery.data?.story && firstStorySeen ? (
                    <div className="story-status-card story-status-card--done">
                      <div className="story-meta" style={{ marginTop: 0, paddingTop: 0, borderTop: 'none' }}>
                        <span className="story-meta__item">Baseada em {storyQuery.data.story.memoryCount ?? successMemories.length} memórias</span>
                        {storyQuery.data.story.updatedAt ? (
                          <span className="story-meta__item">Atualizada {formatRelativeTime(storyQuery.data.story.updatedAt)}</span>
                        ) : null}
                      </div>
                      {storyQuery.data.isOutOfSync ? (
                        <p className="story-out-of-sync-message">Sua história não inclui as alterações mais recentes.</p>
                      ) : null}
                    </div>
                  ) : null}

                  {generateStoryMutation.isPending ? (
                    <div className="story-placeholder-card">
                      <LoadingState label="Estamos escrevendo sua história..." />
                    </div>
                  ) : storyQuery.data?.story ? (
                    <article className="story-card">
                      {storyQuery.data.story.title ? (
                        <h2 className="story-card__title">{storyQuery.data.story.title}</h2>
                      ) : null}
                      <div className="story-card__content">
                        {storyQuery.data.story.content.split(/\n\n+/).filter(Boolean).map((paragraph, idx) => (
                          <p key={idx}>{paragraph.trim()}</p>
                        ))}
                      </div>
                      <hr className="story-card__divider" />
                      <div className="story-actions">
                        <Button type="button" variant="secondary" onClick={handleCopyStory}>
                          Copiar História
                        </Button>
                        <Button type="button" variant="secondary" onClick={() => setIsShareMenuOpen(true)}>
                          Compartilhar
                        </Button>
                        {storyQuery.data.isOutOfSync && successMemories.length >= MIN_MEMORIES_FOR_STORY ? (
                          <Button
                            type="button"
                            disabled={generateStoryMutation.isPending}
                            onClick={handleGenerateStory}
                          >
                            {generateStoryMutation.isPending ? 'Escrevendo sua história...' : 'Atualizar história'}
                          </Button>
                        ) : null}
                      </div>
                    </article>
                  ) : (
                    <div className="story-placeholder-card">
                      <div className="story-placeholder-card__icon">âœ¨</div>
                      <div className="story-placeholder-card__title">Sua história aparecerá aqui</div>
                      {successMemories.length >= MIN_MEMORIES_FOR_STORY ? null : successMemories.length === 2 ? (
                        <p className="story-placeholder-card__desc">Falta apenas 1 memória para gerar sua primeira história.</p>
                      ) : successMemories.length === 1 ? (
                        <p className="story-placeholder-card__desc">
                          Continue registrando momentos importantes.<br />Faltam 2 memórias para gerar sua primeira história.
                        </p>
                      ) : (
                        <p className="story-placeholder-card__desc">
                          Quando você registrar pelo menos 3 memórias,<br />geraremos automaticamente sua primeira história.
                        </p>
                      )}
                    </div>
                  )}
                </div>
              </section>
            </div>

            <div className="home-layout__row home-layout__row--bottom">
              <section className="panel-card panel-card-span">
                <Header
                  title="Timeline"
                  subtitle={
                    memoriesQuery.isFetching
                      ? 'Atualizando...'
                      : memoriesQuery.isLoading || !hasMemoriesData
                        ? 'Carregando...'
                        : `${successMemories.length} memórias`
                  }
                />
                {memoriesQuery.isLoading || (!hasMemoriesData && !memoriesQuery.isError) ? (
                  <LoadingState label="Carregando memórias..." />
                ) : memoriesQuery.isError ? (
                  <EmptyState title="Não foi possível carregar a timeline." description="Verifique sua conexão e tente novamente." />
                ) : allMemories.length === 0 ? (
                  <EmptyState
                    title="Sua timeline está vazia. Escreva a primeira memória."
                    description="Use o card à esquerda para começar a preencher sua história."
                  />
                ) : (
                  <>
                    <ul className="timeline-list">
                      {memories.map((memory) => (
                        <li key={memory.id} className={`timeline-item timeline-item--${memory.status}`}>
                          <div className="timeline-item-header">
                            <div className="timeline-item-header__left">
                              <strong>{getDisplayTitle(memory)}</strong>
                              <span>{formatMemoryDate(memory.createdAt)}</span>
                            </div>
                            <div className="timeline-item-header__right">
                              {memory.status === 'success' ? (
                                <KebabMenu onEdit={() => handleOpenEdit(memory)} onDelete={() => handleOpenDelete(memory)} />
                              ) : null}
                            </div>
                          </div>
                          {memory.isValidationError ? null : <p>{memory.content}</p>}
                          {memory.status === 'pending' ? <span className="timeline-status timeline-status--pending">Guardando...</span> : null}
                          {memory.status === 'error' && memory.isValidationError ? (
                            <div className="timeline-error timeline-error--validation">
                              <p className="timeline-error__msg">{memory.errorMessage ?? 'Não foi possível guardar sua memória.'}</p>
                            </div>
                          ) : null}
                          {memory.status === 'error' && !memory.isValidationError ? (
                            <div className="timeline-error">
                              <p className="timeline-error__msg">{memory.errorMessage ?? 'Não foi possível guardar sua memória.'}</p>
                              {memory.isRetryable ? (
                                <div className="timeline-error__actions">
                                  <Button
                                    type="button"
                                    variant="ghost"
                                    disabled={createMemoryMutation.isPending}
                                    onClick={() => {
                                      track('retry_clicked');
                                      createMemoryMutation.mutate({
                                        userId, title: memory.title, content: memory.content,
                                        eventDate: memory.eventDate, eventYear: memory.eventYear,
                                        clientRequestId: memory.clientRequestId ?? crypto.randomUUID(),
                                      });
                                    }}
                                  >
                                    Tentar novamente
                                  </Button>
                                </div>
                              ) : null}
                            </div>
                          ) : null}
                        </li>
                      ))}
                    </ul>
                    {hasMoreMemories ? (
                      <div className="timeline-show-more">
                        <Button type="button" onClick={handleShowMore}>
                          Ver mais memórias ({allMemories.length - memories.length} restantes)
                        </Button>
                      </div>
                    ) : null}
                  </>
                )}
              </section>
            </div>
          </div>
        </Card>
      </Container>

      <EditMemoryModal
        memory={editingMemory}
        isOpen={isEditModalOpen}
        isSaving={updateMemoryMutation.isPending}
        onClose={handleCloseEdit}
        onSave={handleSaveEdit}
      />
      <ShareMenu
        isOpen={isShareMenuOpen}
        title={storyQuery.data?.story?.title ?? ''}
        text={
          storyQuery.data?.story
            ? storyQuery.data.story.title
              ? `${storyQuery.data.story.title}\n\n${storyQuery.data.story.content}`
              : storyQuery.data.story.content
            : ''
        }
        onClose={() => setIsShareMenuOpen(false)}
      />
      <ConfirmDialog
        isOpen={isDeleteConfirmOpen}
        title="Excluir memória"
        message={deletingMemory ? `Tem certeza que deseja excluir a memória "${getDisplayTitle(deletingMemory)}"? Esta ação não pode ser desfeita.` : ''}
        confirmLabel="Excluir"
        cancelLabel="Cancelar"
        variant="danger"
        isLoading={deleteMemoryMutation.isPending}
        onConfirm={handleConfirmDelete}
        onCancel={handleCloseDelete}
      />
    </main>
  );
}

function formatRelativeTime(isoDate: string): string {
  const now = Date.now();
  const date = new Date(isoDate).getTime();
  const diffMs = now - date;
  const diffMinutes = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMinutes < 1) return 'agora mesmo';
  if (diffMinutes < 60) return `há ${diffMinutes} minuto${diffMinutes === 1 ? '' : 's'}`;
  if (diffHours < 24) return `há ${diffHours} hora${diffHours === 1 ? '' : 's'}`;
  if (diffDays < 30) return `há ${diffDays} dia${diffDays === 1 ? '' : 's'}`;
  return date ? new Date(isoDate).toLocaleDateString('pt-BR') : '';
}
