import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useMyStory } from '../../hooks/useMyStory';
import { useGenerateStory } from '../../hooks/useGenerateStory';
import { useToast } from '../../lib/toast/useToast';
import { track } from '../../lib/track/track';
import type { MemoryUI } from '../../types/memory';

const MIN_MEMORIES_FOR_STORY = 3;

function getFirstStorySeen(): boolean {
  try {
    return localStorage.getItem('firstStoryGenerated') === 'true';
  } catch {
    return false;
  }
}

function markFirstStorySeen() {
  try {
    localStorage.setItem('firstStoryGenerated', 'true');
  } catch {}
}

export type StoryGenerationState = {
  /** All successfully saved memories count */
  successMemories: MemoryUI[];
  /** Whether a story exists and is not the insufficient-content marker */
  hasStory: boolean;
  /** Whether the story content is the insufficient-information marker */
  isInsufficient: boolean;
  /** Whether a generation is in progress */
  isGenerating: boolean;
  /** Whether the first story for this user has been seen */
  firstStorySeen: boolean;
  /** The story data from the API, or undefined */
  storyTitle: string | undefined;
  storyContent: string | undefined;
  storyMemoryCount: number | undefined;
  storyUpdatedAt: string | undefined;
  /** Whether the story is out of sync with current memories */
  isOutOfSync: boolean;
};

export function useStoryGeneration(userId: string, allMemories: MemoryUI[]) {
  const { showToast } = useToast();
  const storyQuery = useMyStory(userId);
  const generateStoryMutation = useGenerateStory();
  const hasAutoGenerated = useRef(false);
  const [firstStorySeen, setFirstStorySeen] = useState(getFirstStorySeen);

  const successMemories = useMemo(
    () => allMemories.filter((m) => m.status === 'success'),
    [allMemories],
  );

  const isInsufficientStory = storyQuery.data?.story?.content === 'INSUFFICIENT_INFORMATION' ||
    storyQuery.data?.story?.content === 'Ainda não há informações suficientes para criar uma história significativa. Adicione mais detalhes às suas memórias.';

  const hasRealStory = !!storyQuery.data?.story && !isInsufficientStory;

  useEffect(() => {
    if (storyQuery.data?.story && !firstStorySeen) {
      setFirstStorySeen(true);
      markFirstStorySeen();
    }
  }, [storyQuery.data?.story, firstStorySeen]);

  // Auto-generation: when user has enough memories but no story yet
  const shouldAutoGenerate = !hasRealStory &&
    successMemories.length >= MIN_MEMORIES_FOR_STORY &&
    !storyQuery.isLoading &&
    !storyQuery.isError;

  // Allow retry when new content is added after an insufficient-content response
  const prevSuccessCountRef = useRef(0);
  if (isInsufficientStory && successMemories.length > prevSuccessCountRef.current && prevSuccessCountRef.current > 0) {
    hasAutoGenerated.current = false;
  }
  if (successMemories.length !== prevSuccessCountRef.current) {
    prevSuccessCountRef.current = successMemories.length;
  }

  useEffect(() => {
    if (
      shouldAutoGenerate &&
      !hasAutoGenerated.current &&
      !generateStoryMutation.isPending
    ) {
      hasAutoGenerated.current = true;
      showToast({
        message: 'Sua primeira história está sendo gerada...',
        variant: 'info',
      });
      generateStoryMutation.mutate(
        { userId },
        {
          onSuccess: () => {
            showToast({
              message: 'Sua primeira história está pronta!',
              variant: 'success',
            });
          },
          onError: () => {
            showToast({
              message: 'Não foi possível gerar sua história agora. Tente novamente mais tarde.',
              variant: 'error',
            });
          },
        },
      );
    }
  }, [successMemories.length, shouldAutoGenerate, userId, generateStoryMutation, showToast]);

  const handleCopyStory = useCallback(() => {
    const story = storyQuery.data?.story;
    if (!story) return;
    const text = story.title ? `${story.title}\n\n${story.content}` : story.content;
    navigator.clipboard.writeText(text).then(() => {
      track('story_copied');
      showToast({ message: 'História copiada com sucesso.', variant: 'success' });
    }).catch(() => {
      showToast({ message: 'Não foi possível copiar a história.', variant: 'error' });
    });
  }, [storyQuery.data?.story, showToast]);

  const handleGenerateStory = useCallback(() => {
    track('story_generate_clicked');
    generateStoryMutation.mutate(
      { userId },
      {
        onSuccess: () => {
          showToast({
            message: 'História atualizada com sucesso.',
            variant: 'success',
          });
        },
        onError: (error: unknown) => {
          const msg =
            error && typeof error === 'object' && 'message' in error
              ? (error as { message: string }).message
              : 'Não foi possível gerar sua história.';
          showToast({ message: msg, variant: 'error' });
        },
      },
    );
  }, [userId, generateStoryMutation, showToast]);

  return {
    state: {
      successMemories,
      hasStory: hasRealStory,
      isInsufficient: isInsufficientStory,
      isGenerating: generateStoryMutation.isPending,
      firstStorySeen,
      storyTitle: storyQuery.data?.story?.title,
      storyContent: storyQuery.data?.story?.content,
      storyMemoryCount: storyQuery.data?.story?.memoryCount,
      storyUpdatedAt: storyQuery.data?.story?.updatedAt,
      isOutOfSync: storyQuery.data?.isOutOfSync ?? false,
    } satisfies StoryGenerationState,
    storyText: storyQuery.data?.story
      ? storyQuery.data.story.title
        ? `${storyQuery.data.story.title}\n\n${storyQuery.data.story.content}`
        : storyQuery.data.story.content
      : '',
    handleCopyStory,
    handleGenerateStory,
  };
}
